---
- name: install ajenti gpg key
  apt_key: url=http://repo.ajenti.org/debian/key state=present

- name: add ajenti deb repository
  apt_repository: repo='deb http://repo.ajenti.org/debian main main debian' state=present

- name: install ajenti package
  apt:
    name: {{ packages }}
    state: latest
    update_cache: yes
    force: yes
  vars:
    packages:
      - ajenti
  notify: restart ajenti

- name: install ajenti v plugins
  apt:
    name: {{ packages }}
    state: latest
    update_cache: yes
    force: yes
  vars:
    packages:
      - ajenti-v
      - ajenti-v-nginx
      - ajenti-v-mysql
      - ajenti-v-php-fpm
      - php5-mysql
  when: ajentiv.enabled
  notify: restart ajenti
